[theme]
base = "light"
primaryColor="#000000"  # Cor primária
backgroundColor = "#FFFFFF"  # Cor de fundo
secondaryBackgroundColor = "#F0F2F6"  # Cor secundária
textColor = "#31333F"  # Cor do texto

primaryColor="#000000"
